user-profile
ectionboy/power-pulse-6-backend pull request #6
Opened 2024-01-13 11:01 UTC by OleksandrTsurkan

Зробив контролери та моделі щодо отримання даних про користувача (група крові, вік, образ життя). Формула розраховує калорії

2024-01-13 14:39 UTC, ectionboy requested changes
![telegram-cloud-photo-size-2-5267253600558633682-y](https://github.com/ectionboy/power-pulse-6-backend/assets/125730248/c8853a79-b3c5-4ce9-b980-3d62802cd6c7)
![telegram-cloud-photo-size-2-5267253600558633683-y](https://github.com/ectionboy/power-pulse-6-backend/assets/125730248/7049aa99-b4c1-4d7a-9519-1e3911358415)
bmr повертається при другому запиті, при першому 0
![telegram-cloud-photo-size-2-5267253600558633685-x](https://github.com/ectionboy/power-pulse-6-backend/assets/125730248/73e9f6a8-6da7-45f1-839e-fd6ea4c0f990)
В helper/index.js розкоментувати підключення модулів dateToShortFormat, calculateBmr
І виправити інші зауваження

2024-01-13 14:39 UTC, ectionboy commented on controllers/profile/createProfile/createProfile.js
> +  // console.log(req.body);
Забрати коментар

2024-01-13 14:39 UTC, ectionboy commented on models/profile.js
> +  currentWeight: Joi.number().min(40).max(160).required(),
currentWeight - number; minimum 35(kg); required
desiredWeight - number; minimum 35(kg); required
Мінімальна вага має бути 35

2024-01-13 17:07 UTC, OleksandrTsurkan commented on models/profile.js
> +  currentWeight: Joi.number().min(40).max(160).required(),
виправив

2024-01-13 17:07 UTC, OleksandrTsurkan commented on controllers/profile/createProfile/createProfile.js
> +  // console.log(req.body);
забрав

2024-01-14 16:40 UTC, ectionboy approved these changes

2024-01-14 18:07 UTC, merged